version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: "Doshboard.Backend/Dockerfile"
    ports:
      - "8080:80"
  client:
    build:
      context: .
      dockerfile: "Doshboard.Frontend/Dockerfile"
    environment:
      - BACKEND_URL=http://server:80/
    ports:
      - "80:80"
    depends_on:
      - "server"